name: Download Files

on:
  workflow_dispatch:
  push:
    paths:
      - 'links.txt'

permissions:
  contents: write

jobs:
  download:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install aria2
        run: |
          sudo apt update
          sudo apt install -y aria2

      - name: Create downloads folder
        run: mkdir -p downloads

      - name: Download files with aria2
        run: |
          grep -v '^[[:space:]]*$' links.txt > urls.txt

          aria2c \
            --input-file=urls.txt \
            --dir=downloads \
            --continue=true \
            --max-connection-per-server=16 \
            --split=16 \
            --min-split-size=1M \
            --max-concurrent-downloads=8 \
            --file-allocation=none \
            --summary-interval=5

      - name: Show downloaded files
        run: |
          echo "Downloaded files:"
          ls -lh downloads/

      - name: Commit files
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          git add downloads/

          git diff --cached --quiet && echo "No changes" || git commit -m "Downloaded new files"

      - name: Push changes
        run: |
          git push
